### ISSUE TITLE
Looking forward to updating the code

### ISSUE THREAD

**Issue by dddeanwang** [arlenejohn/Sleep_apnea_SpO2#1]
I have read your latest paper ’‘SomnNET: An SpO2 Based Deep Learning Network for Sleep Apnea Detection in Smartwatches’‘  in IEEE EMBC 2021, It's really a novel algorithm that I hardly see OSA detection method developed with SpO2 signals. I'll be really appreciated if you can upload the code and models.

**Comment by arlenejohn** [comment]
the code and models have been uploaded

**Comment by dddeanwang** [comment]
thanks！！！
